# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

l4w4/robot_lab:
  model_name: "policy.pt"
  framework: "isaacsim"
  dt: 0.005
  decimation: 4
  num_observations: 57
  observations: ["ang_vel", "gravity_vec", "commands", "dof_pos", "dof_vel", "actions"]
  observations_history: []  # 0 is the latest observation
  clip_obs: 100.0
  clip_actions_lower: [-100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0, -100.0]
  clip_actions_upper: [100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0, 100.0]
  rl_kp: [100.0, 100.0, 100.0,
          100.0, 100.0, 100.0,
          100.0, 100.0, 100.0,
          100.0, 100.0, 100.0,
          0.0, 0.0, 0.0, 0.0]
  rl_kd: [10.0, 10.0, 10.0,
          10.0, 10.0, 10.0,
          10.0, 10.0, 10.0,
          10.0, 10.0, 10.0,
          0.5, 0.5, 0.5, 0.5]
  fixed_kp: [180.0, 180.0, 180.0,
             180.0, 180.0, 180.0,
             180.0, 180.0, 180.0,
             180.0, 180.0, 180.0,
             0.0, 0.0, 0.0, 0.0]
  fixed_kd: [3.0, 3.0, 3.0,
             3.0, 3.0, 3.0,
             3.0, 3.0, 3.0,
             3.0, 3.0, 3.0,
             0.5, 0.5, 0.5, 0.5]
  num_of_dofs: 16
  action_scale: [0.125, 0.25, 0.25,
                 0.125, 0.25, 0.25,
                 0.125, 0.25, 0.25,
                 0.125, 0.25, 0.25,
                 5.0, 5.0, 5.0, 5.0]
  wheel_indices: [12, 13, 14, 15]
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [1.0, 1.0, 1.0]
  torque_limits: [150.0, 150.0, 150.0,
                  150.0, 150.0, 150.0,
                  150.0, 150.0, 150.0,
                  150.0, 150.0, 150.0,
                  30.0, 30.0, 30.0, 30.0]
  default_dof_pos: [ 0.042, 0.8752, -1.5184,
                    -0.042, 0.8752, -1.5184,
                     0.042, 0.9576, -1.4933,
                    -0.042, 0.9576, -1.4933,
                    0.0, 0.0, 0.0, 0.0]
  joint_controller_names: ["FR_hip_controller", "FR_thigh_controller", "FR_calf_controller",
                           "FL_hip_controller", "FL_thigh_controller", "FL_calf_controller",
                           "RR_hip_controller", "RR_thigh_controller", "RR_calf_controller",
                           "RL_hip_controller", "RL_thigh_controller", "RL_calf_controller",
                           "FR_foot_controller", "FL_foot_controller", "RR_foot_controller", "RL_foot_controller"]
  command_mapping: [3, 4, 5, 13, 0, 1, 2, 12, 9, 10, 11, 15, 6, 7, 8, 14]  # find the robot order from the policy order
  state_mapping: [4, 5, 6, 0, 1, 2, 12, 13, 14, 8, 9, 10, 7, 3, 15, 11]  # find the policy order from the robot order
