# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

g1/robomimic/charleston:
  model_name: "dance_0605_aligned.pt"
  num_observations: 94
  observations: ["ang_vel", "gravity_vec", "dof_pos", "dof_vel", "actions", "RoboMimic_Deploy/phase"]
  observations_history: [0, 1, 2, 3]  # 0 is the latest observation
  observations_history_priority: "time"  # "time" or "term" priority
  clip_obs: 100.0
  clip_actions_lower: [-100.0, -100.0, -100.0, -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0, -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0, -100.0, -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0, -100.0, -100.0, -100.0, -100.0]
  clip_actions_upper: [100.0, 100.0, 100.0, 100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0, 100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0]
  rl_kp: [100.0, 100.0, 100.0, 200.0, 20.0, 20.0,
          100.0, 100.0, 100.0, 200.0, 20.0, 20.0,
          400.0, 400.0, 400.0,
          90.0, 60.0, 20.0, 60.0, 20.0, 20.0, 20.0,
          90.0, 60.0, 20.0, 60.0, 20.0, 20.0, 20.0]
  rl_kd: [2.5, 2.5, 2.5, 5.0, 0.2, 0.1,
          2.5, 2.5, 2.5, 5.0, 0.2, 0.1,
          5.0, 5.0, 5.0,
          2.0, 1.0, 0.4, 1.0, 0.4, 0.4, 0.4,
          2.0, 1.0, 0.4, 1.0, 0.4, 0.4, 0.4]
  fixed_kp: [100.0, 100.0, 100.0, 150.0, 40.0, 40.0,
             100.0, 100.0, 100.0, 150.0, 40.0, 40.0,
             300.0, 300.0, 300.0,
             100.0, 100.0, 50.0, 50.0, 20.0, 20.0, 20.0,
             100.0, 100.0, 50.0, 50.0, 20.0, 20.0, 20.0]
  fixed_kd: [2.0, 2.0, 2.0, 4.0, 2.0, 2.0,
             2.0, 2.0, 2.0, 4.0, 2.0, 2.0,
             3.0, 3.0, 3.0,
             2.0, 2.0, 2.0, 2.0, 1.0, 1.0, 1.0,
             2.0, 2.0, 2.0, 2.0, 1.0, 1.0, 1.0]
  num_of_dofs: 29
  action_scale: [0.25, 0.25, 0.25, 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25, 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25]
  wheel_indices: []
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [2.0, 2.0, 0.25]
  torque_limits: [88.0, 88.0, 88.0, 139.0, 50.0, 50.0,
                  88.0, 88.0, 88.0, 139.0, 50.0, 50.0,
                  88.0, 50.0, 50.0,
                  25.0, 25.0, 25.0, 25.0, 5.0, 5.0, 5.0,
                  25.0, 25.0, 25.0, 25.0, 5.0, 5.0, 5.0]
  default_dof_pos: [-0.1, 0.0, 0.0, 0.3, -0.2, 0.0,
                    -0.1, 0.0, 0.0, 0.3, -0.2, 0.0,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  joint_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]
