# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

b2/robot_lab:
  model_name: "policy.pt"
  framework: "isaacsim"
  dt: 0.005
  decimation: 4
  num_observations: 45
  observations: ["ang_vel", "gravity_vec", "commands", "dof_pos", "dof_vel", "actions"]
  observations_history: []
  clip_obs: 100.0
  clip_actions_lower: [-100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0]
  clip_actions_upper: [100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0]
  rl_kp: [100.0, 100.0, 150.0,
          100.0, 100.0, 150.0,
          100.0, 100.0, 150.0,
          100.0, 100.0, 150.0]
  rl_kd: [1.0, 1.0, 1.0,
          1.0, 1.0, 1.0,
          1.0, 1.0, 1.0,
          1.0, 1.0, 1.0]
  fixed_kp: [200.0, 200.0, 300.0,
             200.0, 200.0, 300.0,
             200.0, 200.0, 300.0,
             200.0, 200.0, 300.0]
  fixed_kd: [3.0, 3.0, 3.0,
             3.0, 3.0, 3.0,
             3.0, 3.0, 3.0,
             3.0, 3.0, 3.0]
  hip_scale_reduction: 1.0
  hip_scale_reduction_indices: []
  num_of_dofs: 12
  action_scale: 0.25
  action_scale_wheel: 0.0
  wheel_indices: []
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [1.0, 1.0, 1.0]
  torque_limits: [200.0, 200.0, 320.0,
                  200.0, 200.0, 320.0,
                  200.0, 200.0, 320.0,
                  200.0, 200.0, 320.0]
  default_dof_pos: [ 0.00, 0.80, -1.50,
                     0.00, 0.80, -1.50,
                     0.00, 0.80, -1.50,
                     0.00, 0.80, -1.50]
  joint_controller_names: ["FR_hip_controller", "FR_thigh_controller", "FR_calf_controller",
                           "FL_hip_controller", "FL_thigh_controller", "FL_calf_controller",
                           "RR_hip_controller", "RR_thigh_controller", "RR_calf_controller",
                           "RL_hip_controller", "RL_thigh_controller", "RL_calf_controller"]
  command_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
  state_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
