go2w/robot_lab:
  model_name: "policy.pt"
  framework: "isaacsim"
  dt: 0.005
  decimation: 4
  num_observations: 57
  observations: ["ang_vel", "gravity_vec", "commands", "dof_pos", "dof_vel", "actions"]
  observations_history: []
  clip_obs: 100.0
  clip_actions_lower: [-100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0, -100.0]
  clip_actions_upper: [100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0, 100.0]
  rl_kp: [20.0, 20.0, 20.0,
          20.0, 20.0, 20.0,
          20.0, 20.0, 20.0,
          20.0, 20.0, 20.0,
          0.0, 0.0, 0.0, 0.0]
  rl_kd: [0.5, 0.5, 0.5,
          0.5, 0.5, 0.5,
          0.5, 0.5, 0.5,
          0.5, 0.5, 0.5,
          0.5, 0.5, 0.5, 0.5]
  fixed_kp: [80.0, 80.0, 80.0,
             80.0, 80.0, 80.0,
             80.0, 80.0, 80.0,
             80.0, 80.0, 80.0,
             0.0, 0.0, 0.0, 0.0]
  fixed_kd: [3.0, 3.0, 3.0,
             3.0, 3.0, 3.0,
             3.0, 3.0, 3.0,
             3.0, 3.0, 3.0,
             0.5, 0.5, 0.5, 0.5]
  hip_scale_reduction: 1.0
  hip_scale_reduction_indices: []
  num_of_dofs: 16
  action_scale: 0.25
  action_scale_wheel: 5.0
  wheel_indices: [12, 13, 14, 15]
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [1.0, 1.0, 1.0]
  torque_limits: [23.5, 23.5, 23.5,
                  23.5, 23.5, 23.5,
                  23.5, 23.5, 23.5,
                  23.5, 23.5, 23.5,
                  23.5, 23.5, 23.5, 23.5]
  default_dof_pos: [ 0.00, 0.80, -1.50,
                     0.00, 0.80, -1.50,
                     0.00, 0.80, -1.50,
                     0.00, 0.80, -1.50,
                     0.00, 0.00, 0.00, 0.00]
  joint_controller_names: ["FR_hip_controller", "FR_thigh_controller", "FR_calf_controller",
                           "FL_hip_controller", "FL_thigh_controller", "FL_calf_controller",
                           "RR_hip_controller", "RR_thigh_controller", "RR_calf_controller",
                           "RL_hip_controller", "RL_thigh_controller", "RL_calf_controller",
                           "FR_foot_controller", "FL_foot_controller", "RR_foot_controller", "RL_foot_controller"]
  command_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  state_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
