# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

b2/robot_lab:
  model_name: "policy.pt"
  quaternion: "wxyz"
  num_observations: 45
  observations: ["ang_vel", "gravity_vec", "commands", "dof_pos", "dof_vel", "actions"]
  observations_history: []  # 0 is the latest observation
  clip_obs: 100.0
  clip_actions_lower: [-100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0]
  clip_actions_upper: [100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0]
  rl_kp: [160.0, 160.0, 160.0,
          160.0, 160.0, 160.0,
          160.0, 160.0, 160.0,
          160.0, 160.0, 160.0]
  rl_kd: [5.0, 5.0, 5.0,
          5.0, 5.0, 5.0,
          5.0, 5.0, 5.0,
          5.0, 5.0, 5.0]
  fixed_kp: [200.0, 200.0, 300.0,
             200.0, 200.0, 300.0,
             200.0, 200.0, 300.0,
             200.0, 200.0, 300.0]
  fixed_kd: [3.0, 3.0, 3.0,
             3.0, 3.0, 3.0,
             3.0, 3.0, 3.0,
             3.0, 3.0, 3.0]
  num_of_dofs: 12
  action_scale: [0.125, 0.25, 0.25,
                 0.125, 0.25, 0.25,
                 0.125, 0.25, 0.25,
                 0.125, 0.25, 0.25]
  wheel_indices: []
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [1.0, 1.0, 1.0]
  torque_limits: [200.0, 200.0, 320.0,
                  200.0, 200.0, 320.0,
                  200.0, 200.0, 320.0,
                  200.0, 200.0, 320.0]
  default_dof_pos: [ 0.00, 0.80, -1.50,
                     0.00, 0.80, -1.50,
                     0.00, 0.80, -1.50,
                     0.00, 0.80, -1.50]
  joint_names: ["FR_hip_joint", "FR_thigh_joint", "FR_calf_joint",
                "FL_hip_joint", "FL_thigh_joint", "FL_calf_joint",
                "RR_hip_joint", "RR_thigh_joint", "RR_calf_joint",
                "RL_hip_joint", "RL_thigh_joint", "RL_calf_joint"]
  joint_controller_names: ["FR_hip_controller", "FR_thigh_controller", "FR_calf_controller",
                           "FL_hip_controller", "FL_thigh_controller", "FL_calf_controller",
                           "RR_hip_controller", "RR_thigh_controller", "RR_calf_controller",
                           "RL_hip_controller", "RL_thigh_controller", "RL_calf_controller"]
  command_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]  # find the robot order from the policy order
  state_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]  # find the policy order from the robot order
