# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

go2w_gazebo:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 1000

    # FL Controllers ---------------------------------------
    FL_hip_controller:
        type: robot_joint_controller/RobotJointController
        joint: FL_hip_joint

    FL_thigh_controller:
        type: robot_joint_controller/RobotJointController
        joint: FL_thigh_joint

    FL_calf_controller:
        type: robot_joint_controller/RobotJointController
        joint: FL_calf_joint

    FL_foot_controller:
        type: robot_joint_controller/RobotJointController
        joint: FL_foot_joint

    # FR Controllers ---------------------------------------
    FR_hip_controller:
        type: robot_joint_controller/RobotJointController
        joint: FR_hip_joint

    FR_thigh_controller:
        type: robot_joint_controller/RobotJointController
        joint: FR_thigh_joint

    FR_calf_controller:
        type: robot_joint_controller/RobotJointController
        joint: FR_calf_joint

    FR_foot_controller:
        type: robot_joint_controller/RobotJointController
        joint: FR_foot_joint

    # RL Controllers ---------------------------------------
    RL_hip_controller:
        type: robot_joint_controller/RobotJointController
        joint: RL_hip_joint

    RL_thigh_controller:
        type: robot_joint_controller/RobotJointController
        joint: RL_thigh_joint

    RL_calf_controller:
        type: robot_joint_controller/RobotJointController
        joint: RL_calf_joint

    RL_foot_controller:
        type: robot_joint_controller/RobotJointController
        joint: RL_foot_joint

    # RR Controllers ---------------------------------------
    RR_hip_controller:
        type: robot_joint_controller/RobotJointController
        joint: RR_hip_joint

    RR_thigh_controller:
        type: robot_joint_controller/RobotJointController
        joint: RR_thigh_joint

    RR_calf_controller:
        type: robot_joint_controller/RobotJointController
        joint: RR_calf_joint

    RR_foot_controller:
        type: robot_joint_controller/RobotJointController
        joint: RR_foot_joint
