# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

b2w/robot_lab:
  model_name: "policy.pt"
  num_observations: 57
  observations: ["ang_vel", "gravity_vec", "commands", "dof_pos", "dof_vel", "actions"]
  observations_history: []  # 0 is the latest observation
  observations_history_priority: "time"  # "time" or "term" priority
  clip_obs: 100.0
  clip_actions_lower: [-100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0, -100.0]
  clip_actions_upper: [100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0, 100.0]
  rl_kp: [160.0, 160.0, 160.0,
          160.0, 160.0, 160.0,
          160.0, 160.0, 160.0,
          160.0, 160.0, 160.0,
          0.0, 0.0, 0.0, 0.0]
  rl_kd: [5.0, 5.0, 5.0,
          5.0, 5.0, 5.0,
          5.0, 5.0, 5.0,
          5.0, 5.0, 5.0,
          1.0, 1.0, 1.0, 1.0]
  fixed_kp: [200.0, 200.0, 300.0,
             200.0, 200.0, 300.0,
             200.0, 200.0, 300.0,
             200.0, 200.0, 300.0,
             0.0, 0.0, 0.0, 0.0]
  fixed_kd: [3.0, 3.0, 3.0,
             3.0, 3.0, 3.0,
             3.0, 3.0, 3.0,
             3.0, 3.0, 3.0,
             1.0, 1.0, 1.0, 1.0]
  num_of_dofs: 16
  action_scale: [0.125, 0.25, 0.25,
                 0.125, 0.25, 0.25,
                 0.125, 0.25, 0.25,
                 0.125, 0.25, 0.25,
                 5.0, 5.0, 5.0, 5.0]
  wheel_indices: [12, 13, 14, 15]
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [1.0, 1.0, 1.0]
  torque_limits: [200.0, 200.0, 320.0,
                  200.0, 200.0, 320.0,
                  200.0, 200.0, 320.0,
                  200.0, 200.0, 320.0,
                  20.0, 20.0, 20.0, 20.0]
  default_dof_pos: [ 0.00, 0.80, -1.50,
                     0.00, 0.80, -1.50,
                     0.00, 0.80, -1.50,
                     0.00, 0.80, -1.50,
                     0.00, 0.00, 0.00, 0.00]
  joint_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
